language: go

sudo: false

branches:
  except:
    # skip tags build, we are building branch and master that is enough for
    # consistenty check and release. Let's use Travis CI resources optimally
    # for aah framework.
    - /^v[0-9]\.[0-9]/

go:
  - 1.8
  - 1.8.x
  - tip

go_import_path: aahframework.org/config.v0

install:
  - git config --global http.https://aahframework.org.followRedirects true
  - go get -t -v ./...

script:
  - bash <(curl -s https://aahframework.org/go-test)

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
